# Refer ./setup/baseConfig.yaml for full set of config parameters

config-version: 1.0.0

logging:
  type: syslog
  level: log_warning

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  network-share: true

file_cache:
  path: /<PATH>/<TO>/<CACHE_DIR>
  timeout-sec: 64000000
  allow-non-empty-temp: true
  ignore-sync: true

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: <ACCOUNT_NAME>
  account-key: <ACCOUNT_KEY>
  mode: key
  container: <CONTAINER_NAME>
